version: '3'
services:
  api:
    container_name: api_container
    image: node:14
    working_dir: /usr/src/clean-api
    restart: always
    command: bash -c "npm install --omit=dev --legacy-peer-deps && npm run debug"
    environment:
      - PORT=5050
      - MONGO_URL=mongodb://mongo:27017/clean-api
      - JWT_SECRET_KEY="99sd))_-"
    volumes:
      - ./dist/:/usr/src/clean-api/dist/
      - ./package.json:/usr/src/clean-api/package.json
    ports:
      - '5050:5050'
      - '9222:9222'
    networks:
      - clean-api
 
  mongo:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
    networks:
      - clean-api
 
networks:
  clean-api:
 
volumes:
  mongodb: